# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: "SKKU VR/AR"
title: "프로젝트 가이드"
email: sudo.skkuvr@gmail.com
description: "성균관대학교 VR/AR 동아리 자체 가이드라인 페이지입니다."
baseurl: "/guide"
url: "https://skku-vrar.github.io"
color_theme:  "#178600"
color_text:  "#fff"
language:  "ko"

# Build settings
markdown: kramdown
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 5
exclude:
  - .npmrc
  - package.json
  - yarn.lock